### ISSUE TITLE
App Crash on Pull Service (same reason as LoggingService crash)

### ISSUE THREAD

**Issue by aakash1313** [covidsafe/App-Android#25]
Crash is observed on pull service.

**Comment by justinklchan** [comment]
Did the commit you make resolve the issue? 

I pulled it in, because it doesn't break things, but I noticed you added the boolean state update in 
onHandleIntent and onDestroy

onHandleIntent does not get called (at least on my phone)
onDestroy in general is not guaranteed to be called

https://stackoverflow.com/questions/4449955/activity-ondestroy-never-called

So we shouldn't be updating states in there.

Anyway that boolean state is updated outside the service too.

**Comment by aakash1313** [comment]
@justinklchan : I think i didn't the way service is being, let me investigate. But this is how we should manage intentservices. What that stackoverflow refers to is activity onDestroy, which is not expected to be called always. here we are referring to intent services https://developer.android.com/reference/android/app/IntentService#onDestroy()

**Comment by aakash1313** [comment]
@justinklchan : Constants is not the right way to manage a service state. OnHandleIntent() and onDestroy() are the viable ways to make that happen.

**Comment by aakash1313** [comment]
@justinklchan : Hey did you try to freshly install the app, and put a debug pointer on this method. I see it is being called for me.

**Comment by aakash1313** [comment]
@

**Comment by justinklchan** [comment]
Ok I fixed the issue of onHandleIntent not always being called in a commit.
