### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by ncecere** [covidsafe/App-Android#99]
Are there plans to move the Andriod app to React native like the ios app and merge the code base for the Apps?

**Comment by justinklchan** [comment]
@ncecere The React Native platform in theory speeds up code development since you can write parts of the code base just once, and have that code work on both Android and iOS.

But in practice, React Native is still a relatively nascent platform that is, in my opinion, more challenging to code with, and in many ways slows down development.

In fact, while portions of the codebase can be done in the common React environment, you still have to write many important portions in native code, like the Bluetooth or GPS (which interfaces with platform-specific APIs) anyway.

So you end up having to deal with both native code and the harder-to-program-with React environment.

IMO a big reason why CovidSafe's Android development progressed so quickly was because we fully leveraged the mature Android libraries that were comparatively easy to use, test and debug.

In fact, most of the major contact tracing apps like TraceTogether from Singapore, DP3T from Europe and the Apple/Google API reference implementations and CovidWatch in the US all use native development. MIT's contact tracing app is in the minority for using React Native.

While one could debate the pros and cons of React Native before the project began, there are few benefits to performing a complete overhaul of the codebase (which would introduce many significant bugs that would need testing) when the app's functionality is code complete and has already undergone public testing for bug vetting.
